### PR TITLE
Merged ja, ru, pt languages from collaborators and updated readme

### PR DESCRIPTION
**Pull request by tofi86**
I merged all new language contributions from collaborators @persapiens, @uu and @makatokw and also updated README.rdoc with current URI's to your repo because https://github.com/edavis10/redmine-google-analytics-plugin is deprecated and @edavis10 won't maintain his plugins anymore (see http://projects.littlestreamsoftware.com for details)

The README now points to your repo. Would you like to merge the changes and probably create a [plugin entry on redmine.org](http://www.redmine.org/plugins)?

If you're not interested in hosting/maintaining this plugin anymore, just say and I'll do the job ;-)

### CODE REVIEW

**Comment by tofi86** [comment]
Any chance to merge this in your repo? Or shall I take over the development of the plugin?

**Comment by rkallensee** [comment]
@tofi86 I'm sorry for the delay, missed the notification, now merged! Thanks for the work! :+1: 

I only have a pretty much limited amount of time at the moment. If you want to maintain the plugin, feel free to do so!

**Comment by tofi86** [comment]
Thanks @rkallensee for the merge!

I would take over the project and maintain it in the future if that's okay for you.
Do you want to transfer the repo to my account or leave it as is and post a note at the top which points to my fork? How should we handle this?

I would also add this plugin to the redmine.org plugin repository and credit you as co-author.

**Comment by rkallensee** [comment]
@tofi86 I would say a transfer is not necessary since my version is "just another fork" and not "official" in any way. :smiley: I pointed the link to your repository and also changed the links in the README (see cca75b608c27abf6e5418a0b9aa01e0f461c1461).

**Comment by tofi86** [comment]
Alright, perfect! 😀

**Pull request merged**
